### ISSUE TITLE
Verifying DAY ownership - additional options

### ISSUE THREAD

**Issue by cryogenn** [chronologic/eth-alarm-clock-dapp#234]
Hello - I think there needs to be a different method other than using the keystore file to verify DAY ownership. I doubt everyone will have keystore files since they would not have created their ETH address at MEW or MyCrypto but instead inside Metamask or various wallet apps. Plus I don't think we should have to go and manage a separate ETH address simply to run one dApp, just so that we can have access to a keystore file.

Second, for non developers types such as myself when we go to MyCrypto and their website warns users to not access their wallet using Keystore/JSON files, to then turn around and do that on a third party website seems odd.

**Comment by Bagaric** [comment]
Hi @cryogenn.

First:
One *does not* have to upload a keystore file to *verify the DAY* token balance. The keystore file in question is only used by the TimeNode to store any claimed ETH from scheduling transactions.
The DAY token balance check is done through MyCrypto using *any wallet type* supported by MyCrypto. No keystore upload is needed, only one transaction has to be signed using any wallet method on MyCrypto, I personally use MetaMask. 

Second:
Our DApp is *open-source* and purely *client-side*. If you use the https://app.chronologic.network/ URL you are sure to be running the latest version of the master branch of this repo. 
We still suggest only uploading a keystore file that you want to use purely for the TimeNode, and without a large amount of ETH. Basically, only use a keystore with an amount of ETH on it that you are OK with being there.

If you are still worried, you can always download the DApp and run it locally :) That way you are sure that it will work exactly as written in the code.

Hope this helps. If no further explanation is needed we can close this issue.

**Comment by cryogenn** [comment]
Thanks for the reply but I'm still not following, so bare with me. When I go to this blog post https://blog.chronologic.network/how-to-prove-day-ownership-to-be-a-timenode-3dc1333c74ef it mentions to go here https://app.chronologic.network/timenode as one of the steps. It says to "Select wallet file" and then Unlock.

I don't see any other options available.

**Comment by cryogenn** [comment]
Also, if I export my private key from Metamask into a file and select that file on the website, type in my password and hit unlock, I get an error "SyntaxError: Unexpected token c in JSON at position 0"
![syntax error](https://user-images.githubusercontent.com/19438657/38366654-7f3e5cec-38ae-11e8-8812-83f4d5e929c6.PNG)

**Comment by Bagaric** [comment]
Hi @cryogenn, sure no problem. The keystore file is a necessity in order for the TimeNode the run, but the keystore file itself does not have to contain DAY tokens. DAY token check can be done on a different wallet of your choice, that's why we point to MyCrypto. 

Basically what we require is:

1. **Keystore file** 
- for executing scheduled transactions and storing the claimed ETH into that wallet 
- can (even should) be entirely empty with a balance of 0 ETH.

<img width="1247" alt="screen shot 2018-04-05 at 19 49 36" src="https://user-images.githubusercontent.com/9353642/38366728-f031ed7c-390a-11e8-8fb0-ef9cb85078ff.png">

2. **Message signed with an (arbitrary) account holding DAY tokens** 
- For this we point to MyCrypto
- Use the wallet of your choice to sign the message, the account should hold DAY tokens 
<img width="1254" alt="screen shot 2018-04-05 at 19 49 11" src="https://user-images.githubusercontent.com/9353642/38366788-18b590f0-390b-11e8-872e-2e1416390fac.png">

**Comment by Bagaric** [comment]
@cryogenn As far as the MetaMask private key file is concerned, it is not supported yet.
Please generate a new wallet from https://mycrypto.com/ and use that one.

**Comment by cryogenn** [comment]
Your second reply about the MetaMask private key not being accepted yet. Would you know if you will allow it to be accepted before your team goes live with the time node? I'm just trying to remove one hoop from the process and have no problem waiting until that happens.

It just seems like extra to create an ETH wallet to use with one dApp

But if you plan on making the process easier later on, I can always wait until that time comes.

**Comment by cryogenn** [comment]
@Bagaric I guess it doesn't really matter when you add MetaMask key file support, I'll just continue to follow the project and see when it is added and then setup the time node at that point. So I'll hold off on setting anything up until that is done.

Thanks for the help otherwise. You can close the issue.

**Comment by Bagaric** [comment]
Thanks for the suggestions @cryogenn! We'll look into it :) If you have any other issues or uncertainties, feel welcome to open another issue.
