### ISSUE TITLE
Someone else received bounty

### ISSUE THREAD

**Issue by johnbassplayer** [chronologic/eth-alarm-clock-dapp#763]
My node executed, deposit was returned and someone else got paid.

[https://etherscan.io/tx/0x94c1f99d0a08ed2aaeb1d321a91f30b8cbd55de13239b1cf66dd18e588d79a2b](url)

[logtm02102018.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2443956/logtm02102018.txt)
[logtm02102018b.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2443957/logtm02102018b.txt)
![2018-10-02](https://user-images.githubusercontent.com/40284141/46440893-bb69ec80-c75c-11e8-9477-45392ee3ae45.png)

@lsaether 
@kosecki123

**Comment by kosecki123** [comment]
Let me break this down:

![image](https://user-images.githubusercontent.com/5417665/46475742-a5087300-c7e6-11e8-8746-7792a44836dd.png)

We have 3 transfers here:

1) An amount that was scheduled and sent to designated destination
2) An amount that was sent to TimeNode (0x2ca4a62baa04361b4c9ab2127e457ba862b4d917) that executed the tx
3) The remaining amount of ETH that was sent back to the address that scheduled

Now the remaining amount of ETH is due to:
1) Person that scheduled sent more ETH than required
2) Person that scheduled payed for more GAS that it was used upon the execution
3) The part of bounty that wasn't claimed (due to payment modifier lower than max = 1). _For e.g the bounty was set to 1ETH, the TimeNode claimed with payment modifier 0.1. That results in 0.1ETH payed to TimeNode, 0.9ETH sent back to address that scheduled_

Let me know if that's clear. I don't think it an issue, rather misunderstanding of the protocol.

**Comment by johnbassplayer** [comment]
Are you referring to BRING A PROFIT HIGHER THAN when you mentioned payment modifier? 
Was believing that this was the minimum I'd take action for, not that difference of ETH above this number would be returned back to who scheduled.

**Comment by johnbassplayer** [comment]
Makes sense now. Thank you for clarifying .
